[package]
authors = [
  "Barugon <barugon@dungeonbox.net>",
  "Elias Kartashov <elias@lowenware.com>",
]
description = "File dialog window for egui"
edition = "2021"
keywords = ["file-dialog", "file-picker"]
license = "MIT"
name = "egui_file"
repository = "https://github.com/Barugon/egui_file"
version = "0.18.0"

[dependencies]
nih_plug_egui = { git = "https://github.com/ardura/nih-plug.git", rev = "bd0da5e936a213747c29c00d60310578c0907006" }
